### PR TITLE
Maintenance

### PR DESCRIPTION
**Pull request by mahdiyazdani**
This PR upgrades some of the outdated node modules and removes the unnecessary functionality in regards to compiling resources.

### CODE REVIEW

**Comment by mahdiyazdani** [comment]
@gooklani Please investigate why we are unable to update the `postcss-nested` package to the latest release available.

`npm install postcss-nested@5.0.5 --save-dev`

**Comment by mahdiyazdani** [comment]
@gooklani Please check for the styling issues caused by recent updates. Thank you!

**Comment by gooklani** [comment]
> @gooklani Please check for the styling issues caused by recent updates. Thank you!

Thank you 😊 I will check the styling issues later today

**Comment by gooklani** [comment]
@mahdiyazdani The cause of styling issues was unsupported PostCSS plugins (`postcss-combine-media-query`, `postcss-extend`). I have uninstalled the plugins and replaced the defined placeholders with mixin.

**Comment by mahdiyazdani** [comment]
@gooklani Thank you! Have we resolved all the styling issues caused by the recent updates?

**Comment by gooklani** [comment]
> @gooklani Thank you! Have we resolved all the styling issues caused by the recent updates?

Indeed

**Pull request merged**
